server:
  port: 8100
  servlet:
    context-path: '/scheduler'

message:
  source:
    location:
      bundle: 'messages/scheduler_messages'
      common: 'messages/scheduler_messages_common.properties'
    locale-setting:
      fallback: 'ru-RU'
